### ISSUE TITLE
CNN accelerator results disposition

### ISSUE THREAD

**Issue by Gio200023** [MaximIntegratedAI/ai8x-training#158]
Hi there!

I'm trying to understand how weights are multiplied with the input from previous layer in the CNN accelerator. 
So far I understand that, as you can see in the image below taken from the mnist examples, in the kernel map is explained how many kernels each layer takes into account when doing the convolution. In the example below I'm talking about the last layer.
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/75630696/177786105-ece96c3f-ab5b-4be7-8dc1-a2b629a124b6.png">
From the kernel map of the last layer you can understand that the input size is 12 (which is correct) and the output channels would be 18 when in fact are just 10.Is that an error?
I read the things just mentioned above form here:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/75630696/177791211-79483ada-3a82-4762-a113-42a3187825ff.png">

In addition I took the weights in the weights.c file and translate from hex numbers to mod2 numbers with the formula given in the README. Then I tried to convolve them with the flatten layer 192x1x1 but the results don't add up.

These are the first kernel of the last layer's weights turn into mod2: 

```
weights_last=np.array([-28,12,-7,-107,44,94,46,-69,-1,-53,-68,-16,9,-3,9,11,-56,-56,-69,-11,-43,-8,0,9,59,-26,-18,-50,12,7,31,19,-7
,30,-3,20,28,-5,-31,25,-30,-58,-43,8,-10,16,8,17,-4,31,28,-40,72,22,22,12,81,12,-62,43,-31,-49,-89,42,-33,61,77,21,-22,19,-26,-15,
-16,-18,-7,-3,65,-3,-55,-25,40,71,63,62,-118,55,56,79,-119,-116,-72,-116,74,95,50,-121,84,97,99,51,111,-54,42,124,-60,-73,-5,125,8
8,74,59,33,40,51,33,39,-1,-49,-102,-5,36,-4,-19,-6,-94,-128,-31,-58,70,53,22,-10,-15,-121,-71,77,-78,-88,-128,-108,-76,-88,-128,-
128,90,29,51,60,57,84,49,22,25,0,0,25,43,20,74,38,0,0,81,83,-23,14,81,-1,36,11,73,37,-47,52,109,37,-17,-11,-40,-13,108,49,-46,-23,1
26,127,49,55,-5,80,31,80])

```

I tried to multiply them with the flatten layer, which is:

```
flatten = [127, 127, 127 , 68 ,127, 127, 127 ,127 , 62,  24,  11,   0 ,  0 ,  0 ,  0 ,  0,  11 ,  8,  25,  58,  94, 105,  52 , 98 , 99 ,127,  
38 , 43,  60, 127 , 36 ,  0, 127 ,127 ,127 ,110 ,113, 107,  86,  59,   0  , 0  , 0 , 34 ,  0  , 0  , 0, 29  , 0 , 15  , 3  ,36  , 0  , 0  , 0 , 61  , 0  , 0 
,  0 ,  0  , 0  , 0  , 0  , 0  , 0  , 0  , 0 , 42 , 17   ,0  , 0  , 0 , 59 , 91 ,  0 ,  0 , 49 , 45  , 0  , 0 , 52 , 15 , 33 , 57  , 0  , 0 , 22  , 0  , 0  , 9  , 0  
, 0 , 46  , 2, 0 , 24, 127, 127, 109  , 0, 127, 127, 127  , 0 , 89  ,64 , 46 , 52 , 56 , 73, 127, 115, 127, 127 , 93 , 66, 127, 127, 105 , 10, 127 , 
81  , 0  , 0 , 56  , 0 , 12 , 51  , 0 ,  0,  32  , 0  , 0  , 0  , 0  , 0 , 44, 127, 109, 127 , 48, 127, 127, 127 ,  0 , 34 , 47 , 35  , 0  , 0  , 0 , 53 , 52  
, 0  , 0  , 0  , 0  , 0   ,0  , 0 , 82, 100 ,126, 101, 104, 127, 127 , 20, 127, 127, 127 , 59 , 86, 127, 127 , 29  ,61 ,127, 127, 127, 111, 127, 127, 
127, 127, 127 , 74  , 0 ,113 , 86  , 2  , 0]
```

But the result are very different from the one in the log.txt file, which is:

```
-77992   
```

and to me the output was:

```
99297
```

When instead I multiply and sum the flatten layer (mentioned above) with the output channel 0 of the last layer it result something similar:
```
output_channel_0=np.array([-16,44,94,46,-69,-28,12,-7,-107,-69,-11,9,-3,9,11,-1,37,36,11,73,37,-23,14,81,-1,-46,-23,-17,-
11,-40,-13,-47,-22,-17,64,82,-11,-10,65,113,1,44,115,126,41,74,126,104,17,2,-11,-28,-14,-72,-74,-45,-53,-116,-124,-34,-8,-
69,-75,-25,70,40,-11,-46,41,19,-120,-115,35,30,-118,-122,23,13,-80,-73,40,89,104,40,62,106,109,-15,52,119,75,-28,52,73,
37,0,12,13,33,8,-15,-9,-10,-54,-60,-96,-74,-71,-15,-56,-47,-26,4,82,112,94,-89,-22,124,125,-126,-126,73,101,-114,-83,69,
69,8,-37,-34,17,45,-17,-49,5,5,-6,-29,17,-16,-77,-84,-23,-29,-42,-35,13,-42,-54,-56,-12,-14,-32,23,78,-34,1,94,115,0,6,5,
-9,-48,-57,-36,-38,-58,-57,-23,-45,-33,-42,2,10,-23,9,60,4,-28,1,32,-34,-45,-50,-28,-42,-47,-63,-13,-14])
```
result:
```
-80808
# if I add bias:
-80808 +22 = -80786
```

Which make no sense to me because the output channel 0 should be the output of the last layer in the first channel, right? 

My final goal is to update the weights and add neurons to the last layer with an Online learning technique, so I need to understand how the weights are being used.
In the README is explained that the multiplication with a flatten layer occur with the first weights that match the length of the input flatten array. 
Example: the layer is 192x1x1 long and is multiply with the first 192 mod2 weights taken from the first 192/4=48 hex values.
Is it correct? 
Can you explain to me how the last layer convolve with the weights and how the results are compute?

Thank you!

**Comment by rotx-maxim** [comment]
The input dimensions of the last layer are 4x4 (before flattening), and the last layer has 12 input channels as well as 10 output channels.
Furthermore, the kernel dimensions are 1x1. Each element in the "kernel map" can hold one 3x3 kernel or nine 1x1 kernels.
So, we need 12x4x4x10 bytes of kernel data or 12x17.777 72-bit kernels which rounds up to the 12x18 you're seeing in the map.

To better understand the math, my recommendation would be to use log.txt (possibly with additional verbosity switches).
Look for "FLATTEN TO 192x1x1:"
Channels #0 to #191
[127 127 127  68 ....]
1x1 KERNEL(S):
Output channel #0
[ -16   44   94   46  -69  -28   12 ...]
BIAS: [ 22  28 -28 -35  19  -9 -32 -10  31   8]
10x1x1 FULL-RES OUTPUT:
[ -77992   93377   45484   29850  -36248 -130974 -272399  416616 -148783   25073]

weights.h will look slightly different depending on how new your tools are. The very latest version creates the following:

#define BIAS_0 { \
  0x16, 0x1c, 0xe4, 0xdd, 0x13, 0xf7, 0xe0, 0xf6, 0x1f, 0x08 \
}
#define KERNELS { \
  0x50180000, 0x00000087, 0x33110429, 0xf6ea2cf4, 0xf7760e1b, 0xf080e006, 0x15410ec4, 0xcc1e297d, \
  0xfff0deed, 0xf324e87f, 0xc01f5b80, 0xfe0023ed, 0xfa182b27, 0x301ed9e2, 0x2a2be5ed, 0x1a480301, \
....

The bias values correspond directly to what you see in log.txt (since they're used in only that last layer), and the kernels are address - length - data. Since they're not broken up by layer you'll have to do some additional work to get them separated for the last layer.

If you want to follow the example math, you can follow the code in izer/simulate.py. Let me know if you get stuck.
