### ISSUE TITLE
`.bin_storage' will not fit in region `FLASH'

### ISSUE THREAD

**Issue by oussemajelassi** [MaximIntegratedAI/ai8x-training#166]
Hello again,
I was following these instructions : https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/Guides/Making%20Your%20Own%20Audio%20and%20Image%20Classification%20Application%20Using%20Keyword%20Spotting%20and%20Cats-vs-Dogs.md

I wanted to add a new label to the dataset and completed all the mentioned steps, When I build the code i faced this problem.
"  `.bin_storage' will not fit in region `FLASH'   "
What did I wrong ?

**Comment by aniktash** [comment]
This is generally when the code size is too big to fit in the flash. Mostly happens when sampledata.h size is large and cannot be included as a header file. In KWS case, since the model is not changed and the size of sample data is the same, it should not happen. You may try once to go through the steps just as is without adding a new label, to verify it's working.

**Comment by aniktash** [comment]
You can then do a diff between the two generated codes to see anything causing the code size to grow so much beyond the flash

**Comment by oussemajelassi** [comment]
In my case I noticed that weights.C is too big 1160 Kb compared to 660 Kb

**Comment by aniktash** [comment]
Make sure you are using the same model (v3). You might have used a different model (v2 is about 11.1kb)

**Comment by oussemajelassi** [comment]
Yes indeed i used that one v2
