### ISSUE TITLE
--save-sample for Object Detection creates 0.00 

### ISSUE THREAD

**Issue by ryalberti** [MaximIntegratedAI/ai8x-training#199]
Hello,

I posted this as a comment on #135 but it's closed so I didn't know if it would be seen. 

I'm training an object-detection model and I'm experiencing a related issue. When I add --save-sample, my mAP goes to 0.0000. Attached (ex.1 , ex.2) are some of my tests. Additionally, I tried the changed train file in PR https://github.com/MaximIntegratedAI/ai8x-training/pull/136 and I am still receiving a lower mAP than I have in previous continuations (ex.3). I also have a control example with the unedited SVHN_74_simplified with the changed train.py (ex.4).

When I use the samples from the different train.py's in the synthesis quantize and generation, they receive the same output which I have in ex.4. They are both using checkpoints from the same previous svhn training session with the original training script. 

Are there any differences with object detection in this way?

Thanks for the help!

[sample_examples.zip](https://github.com/MaximIntegratedAI/ai8x-training/files/10198513/sample_examples.zip)

**Comment by seldauyanik-maxim** [comment]
* Indeed the changes mentioned in PR 136 seem to fix the issue and I opened a fresh PR #201 on that
* Would you mind using --deterministic option for your trials with and without --save-sample option. As the logs are cut out for the very initial epochs, they can vary independent of the --save-sample option but due to random initialization. 

   I am attaching two logs of the two experiments I regenerated using the very similar train.py parameters you are using with only the addition of --deterministic option. Both experiment logs output identical mAP values (second one only has --save-sample additional option)

     - ` python train.py --deterministic --print-freq 200 --epochs 20 --optimizer Adam --lr 0.050 --model ai85tinierssd --use-bias --dataset SVHN_74_simplified --device MAX78000 --wd 0 --momentum 0.9 --weight-decay 5e-4 --obj-detection --obj-detection-params parameters/obj_detection_params_svhn.yaml --qat-policy policies/qat_policy_svhn_short.yaml --validation-split 0  --confusion --batch-size 16 --data /data/`
     - ` python train.py --deterministic --print-freq 200 --epochs 20 --optimizer Adam --lr 0.050 --model ai85tinierssd --use-bias --dataset SVHN_74_simplified --device MAX78000 --wd 0 --momentum 0.9 --weight-decay 5e-4 --obj-detection --obj-detection-params parameters/obj_detection_params_svhn.yaml --qat-policy policies/qat_policy_svhn_short.yaml --validation-split 0  --confusion --batch-size 16 --data /data/ --save-sample 10`


[sample_training_logs.zip](https://github.com/MaximIntegratedAI/ai8x-training/files/10219168/sample_training_logs.zip)

**Comment by ryalberti** [comment]
I had the same results with the above scripts. Looking closer at some of my previous tests, it looks like this has been the same across other files. It looks like I'm noticing unrelated fluctuations. 
Thanks for your help!
[with_sample_2022.12.13-201045.log](https://github.com/MaximIntegratedAI/ai8x-training/files/10228733/with_sample_2022.12.13-201045.log)
[without_sample_2022.12.13-101819.log](https://github.com/MaximIntegratedAI/ai8x-training/files/10228737/without_sample_2022.12.13-101819.log)
