### ISSUE TITLE
modification of fpn-detector yaml for different number of classes

### ISSUE THREAD

**Issue by nikky4D** [MaximIntegratedAI/ai8x-training#236]
how do I modify the network yaml in ai8x-synthesis/networks folder for the ai8x_fpndetector.py model trained on pascal voc? I am using the same model but the number of channels input was updated from 3 to 1. 

I am able to train the model with ai8x-training, and evaluate the quantized version. However, when running gen_demos_...sh I am getting an error that ```Layer52 (class_preds_from_32_40) : 12 output channels using 1 pass (12 processors per pass), but the processor output map 0xffffffff[etc] has 64 bits instead of the expected number of 12) ```

Can you point me to which part of the yaml for the network should be updated with a change in the class number? Also, is there a program that generates this yaml file?

**Comment by rotx-maxim** [comment]
Could you share your code please?
From the error message, it could be that the first layer needs to be adjusted. "processors: 7" in layer 0 should probably be "processors: 1" and the weights/model for that layer would need to match. Since that very first layer is a conv2d with 64 output channels, no other changes should be necessary.
Generally, you need one "processor bit" per channel. In the case of the original network, the output of the class_preds_from_32_40 layer is 6*21=126 32-bit channels, or a 2x multipass with 64 processors. Since the only expected changes are in the first layer, I suspect a mismatch between model/weights/data and the network description.
