### ISSUE TITLE
Training killed KWS20

### ISSUE THREAD

**Issue by matti122** [MaximIntegratedAI/ai8x-training#257]
Hello,
I'm trying to train KWS20 Demo on my System.

My the scripts start to train the Model, every time the system kills the process.
Here is the Screenshot with the message out of memory:
![Screenshot from 2023-09-28 13-20-01](https://github.com/MaximIntegratedAI/ai8x-training/assets/2665858/088a260e-c3d7-471f-9c05-afaca7fd6b9a)

Here are some additional information about my system:
RAM 16Gb
Ubuntu 22.04
Geforce 4060
Cuda 11.8 with latest graphic card Driver 535

Could you please help
Thanks and best regards

**Comment by alicangok** [comment]
In our experiments, loading the full Google Speech Commands dataset with the augmentations initially consumes just over 16GB of memory, and falls to a steady state RAM usage of ~10 GB.

I would strongly suggest upgrading your RAM if possible.

If not, you could go to the `raw` directory in your data directory, and delete some of the remaining 15 classes (e.g. "sheila", "follow"), or the `librispeech` examples that we added as background for robustness. Once you do this, delete te old processed dataset (`processed/dataset2.py`), comment out [these](https://github.com/MaximIntegratedAI/ai8x-training/blob/8e20231c76ecf7c0dfa242f92eb14a8252a5444d/datasets/kws20.py#L181C1-L195) lines so that next time you run the training script, it will regenerate the processed dataset with fewer examples.

Also, if you could you provide the generated log file for your future queries, that would make it easier to pinpoint exactly where the process is killed.

**Comment by matti122** [comment]
I have increased the swap memory and now it is working.
